PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf001','indias-emerging-technology-frontiers','India''s Emerging Technology Frontiers','','technology','analysis','BHARAT FRONTIERS Editorial Desk',NULL,'An evidence-led look at the technologies, research ecosystems and industrial capabilities shaping India''s next technology frontier.','technology-frontiers.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf002','research-in-the-next-decade','Research in the Next Decade','','science','analysis','BHARAT FRONTIERS Editorial Desk',NULL,'How research priorities, institutions, talent and infrastructure can shape the next decade of discovery and application.','research-next-decade.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf003','frontiers-of-modern-scientific-research','The Frontiers of Modern Scientific Research','','science','feature','BHARAT FRONTIERS Editorial Desk',NULL,'A clear guide to the changing boundaries of scientific research and the tools expanding what researchers can investigate.','scientific-research.png','','draft','0','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf004','how-research-becomes-innovation','How Research Becomes Innovation','','research','explainer','BHARAT FRONTIERS Editorial Desk',NULL,'Understanding the path from research and discovery to prototypes, products, services and measurable public value.','research-innovation.png','','draft','0','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf005','artificial-intelligence-from-tool-to-infrastructure','Artificial Intelligence: From Tool to Infrastructure','','technology','feature','BHARAT FRONTIERS Editorial Desk',NULL,'Why AI is increasingly being understood as an infrastructure layer involving data, compute, models, applications, skills and governance.','ai-infrastructure.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf006','semiconductors-and-strategic-technology','Semiconductors and Strategic Technology','','technology','analysis','BHARAT FRONTIERS Editorial Desk',NULL,'An accessible examination of semiconductor design, fabrication, packaging, supply chains and industrial capability.','semiconductors.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf007','governing-emerging-technologies','Governing Emerging Technologies','','policy','analysis','BHARAT FRONTIERS Editorial Desk',NULL,'The policy questions raised when new technologies affect data, competition, safety, infrastructure, innovation and society.','technology-policy.png','','draft','0','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf008','can-deep-tech-become-big-business','Can Deep-Tech Become Big Business?','','business','analysis','BHARAT FRONTIERS Editorial Desk',NULL,'How research, intellectual property, capital, startups, manufacturing and markets interact in deep-tech commercialisation.','deep-tech-business.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf009','from-laboratory-to-society','From Laboratory to Society','','research','feature','BHARAT FRONTIERS Editorial Desk',NULL,'The journey from scientific research to real-world applications across healthcare, energy, agriculture, mobility and public services.','laboratory-to-society.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf010','what-is-a-semiconductor','What Is a Semiconductor?','','explainer','explainer','BHARAT FRONTIERS Editorial Desk',NULL,'A plain-language explanation of semiconductors, chips, wafers, fabrication and why these technologies matter.','what-is-a-semiconductor.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
INSERT OR IGNORE INTO articles (id,slug,title,subtitle,section,type,author,published_at,summary,image,content_html,status,featured,issue,created_at,updated_at) VALUES ('bf011','technology-ambition-to-technological-capability','Can India Turn Technology Ambition Into Technological Capability?','','analysis','analysis','BHARAT FRONTIERS Editorial Desk',NULL,'An evidence-based framework for examining the relationship between policy, funding, research, talent, infrastructure and industry.','technology-ambition.png','','draft','1','001','2026-09-18T00:00:00.000Z','2026-09-18T00:00:00.000Z');
